Fix VM init failure due to wrong java.home on OpenJDK/Darwin
When built for OpenJDK on Darwin, VM fails during init:

  Exception occurred while VM initialising.
  java/lang/NoClassDefFoundError: java/lang/ClassLoader

This is due to an invalid value being derived for java.home:
Both classlibDefaultJavaHome() and classlibDefaultBootDllPath()
expect the java.home directory to be 4 path components up from
the location of libjvm. This is correct on most platforms where
libjvm lives at <java.home>/lib/<arch>/<vmname>/libjvm.so [1],
but not on Darwin, where there is no architecture subdirectory
and libjvm lives at <java.home>/lib/<vmname>/libjvm.dylib [2].

Fix by adjusting the lookup code in classlibDefaultJavaHome()
and classlibDefaultBootDllPath() on Darwin.

 [1]: https://github.com/openjdk/jdk8u/blob/jdk8u482-ga/jdk/src/solaris/bin/java_md_solinux.c#L792
 [2]: https://github.com/openjdk/jdk8u/blob/jdk8u482-ga/jdk/src/macosx/bin/java_md_macosx.c#L591

Signed-off-by: Guillermo Rodríguez <grodriguez@ingelabs.com>