Fix os.name for OpenJDK/Darwin (macOS)
When built for OpenJDK on Darwin, trying to run a simple Hello
World application on macOS fails:

  java.lang.AssertionError: Platform not recognized
      at sun.nio.fs.DefaultFileSystemProvider.create(...)

This is because JamVM sets os.name from uname(), which returns
"Darwin". However, the expected value for macOS is "Mac OS X"
(see [1], [2]). This breaks any code that relies on os.name to
detect macOS, including parts of the OpenJDK class library itself
(e.g. DefaultFileSystemProvider).

 [1]: https://bugs.openjdk.org/browse/JDK-8004646
 [2]: https://developer.apple.com/library/archive/technotes/tn2002/tn2110.html

Signed-off-by: Guillermo Rodríguez <grodriguez@ingelabs.com>